name: "[Release] Tests"
run-name: Run Release Test Suite
on:
  pull_request:
    branches:
      - v**
jobs:
  trigger_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout
      - name: sometests
        run: |
          echo "Perform any tests on the branch, confirm stability. If issues are found, they should be corrected in `main/master` and be cherry-picked into this branch."
